version: 1.0.{build}-{branch}
skip_tags: true
image: Visual Studio 2019 Preview
cache: tools -> build.cake, tools/packages.config

build_script:
  - ps: .\build.ps1 -target AppVeyor
test: off
artifacts:
  - path: BuildOutput/Artifacts/*.nupkg
    name: Package

for:

-
  branches:
    only:
      - master
      - /release\/.*/
      - /hotfix\/.*/
  deploy_script:
    - ps: .\build.ps1 -target DeployLibrary